version: "3.1"
services:
    my_drupal:
        image: drupal
        ports: 
            - "80:8080"
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
    my_posgres:
        image: postgres
        environment:
            - "POSTGRES_PASSWORD=mypass"

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes: