version: "3.1"

services:
    psql:
    secrets:
        - psql_user
        - psql_password
    environment:
        POSTGRES_USER_FILE: /run/secrets/psql_user
        POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
secrets:
    psql_user:
        file: ./psql_USER.txt
    psql_password:
        file: ./psql_PASS.txt


networks:
    - frontend
    - backend

volumes:
